### PR TITLE
Small fix for ff121

### PR DESCRIPTION
**Pull request by 117649**
alternative_searchbar.uc.js ff121 fix

### CODE REVIEW

**Comment by Aris-t2** [comment]
This seems to cause an issue were search through searchbar stops working entirely or is it just me?

**Comment by 117649** [comment]
> This seems to cause an issue were search through searchbar stops working entirely or is it just me?

This is meant to fix such issue if it was only caused by this script. And It tested working on my devEd env.

If you have other source modified ```doSearch()``` this won't fix those all together. You have to carry on and fix those. 
For example TMP also modified ```doSearch()``` if you happened to also use that you have to update it to the newest test build.

**Comment by 117649** [comment]
@Aris-t2 Hi just update to 122 and seems on 122 you have to revert this to not cause problem......

**Comment by Aris-t2** [comment]
No problem, I've added a workaround without stealing browsers default doSearch.

**Pull request merged**
